# Generated by Django 3.1 on 2020-08-14 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(editable=False, max_length=10, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
            ],
        ),
    ]
