# Generated by Django 3.1 on 2020-08-16 00:27

import core.models.video
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(editable=False, max_length=10, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(editable=False, max_length=10, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(editable=False, max_length=10, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(editable=False, max_length=10, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('link', models.URLField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Lemuel\\Projects\\Screw_Youtube\\temp\\videos\\original'), upload_to=core.models.video.update_filename, verbose_name='Video')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PRO', 'Processing'), ('UPL', 'Uploading'), ('REA', 'Ready')], default='NEW', max_length=3)),
                ('playlist', models.ManyToManyField(blank=True, to='core.Playlist', verbose_name='Playlist')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.series', verbose_name='Series')),
                ('tag', models.ManyToManyField(blank=True, to='core.Tag', verbose_name='Tag')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.video', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalVideo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, editable=False, max_length=10, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(blank=True, editable=False, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(blank=True, editable=False, verbose_name='Date modified')),
                ('link', models.URLField(blank=True, null=True)),
                ('video', models.TextField(blank=True, max_length=100, null=True, verbose_name='Video')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PRO', 'Processing'), ('UPL', 'Uploading'), ('REA', 'Ready')], default='NEW', max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.series', verbose_name='Series')),
            ],
            options={
                'verbose_name': 'historical video',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, editable=False, max_length=10, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(blank=True, editable=False, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(blank=True, editable=False, verbose_name='Date modified')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tag',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSeries',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, editable=False, max_length=10, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(blank=True, editable=False, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(blank=True, editable=False, verbose_name='Date modified')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Series',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlaylist',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, editable=False, max_length=10, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(blank=True, editable=False, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(blank=True, editable=False, verbose_name='Date modified')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical playlist',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='thumbnail',
            constraint=models.UniqueConstraint(fields=('video', 'position'), name='unique_position'),
        ),
    ]
