# Generated by Django 3.1 on 2020-08-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='image',
        ),
        migrations.AddField(
            model_name='historicalvideo',
            name='public_url',
            field=models.URLField(blank=True, null=True, verbose_name='Public URL'),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='public_url',
            field=models.URLField(blank=True, null=True, verbose_name='Public URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='public_url',
            field=models.URLField(blank=True, null=True, verbose_name='Public URL'),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='link',
            field=models.URLField(blank=True, help_text='For example, this can link to the IMDB page of the video.', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, help_text='For example, this can link to the IMDB page of the video.', null=True, verbose_name='Link'),
        ),
    ]
