# Generated by Django 3.1 on 2020-08-20 02:55

import core.helpers.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200818_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltag',
            name='colour',
            field=models.CharField(default=core.helpers.helper.random_colour, max_length=7, verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='tag',
            name='colour',
            field=models.CharField(default=core.helpers.helper.random_colour, max_length=7, verbose_name='Colour'),
        ),
    ]
