# Generated by Django 3.1 on 2020-08-14 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_historicalplaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(editable=False, max_length=10, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, editable=False, max_length=10, verbose_name='URL')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default='PRI', max_length=3)),
                ('date_added', models.DateTimeField(blank=True, editable=False, verbose_name='Date added')),
                ('date_modified', models.DateTimeField(blank=True, editable=False, verbose_name='Date modified')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tag',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
