# Generated by Django 3.1 on 2020-08-22 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20200820_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlaylistVideo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, verbose_name='Position')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical playlist video',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, verbose_name='Position')),
            ],
            options={
                'ordering': ['video', 'position'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='thumbnail',
            name='unique_position',
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlist',
        ),
        migrations.AlterField(
            model_name='historicalplaylist',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='colour',
            field=models.CharField(blank=True, max_length=7, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(blank=True, max_length=7, verbose_name='Colour'),
        ),
        migrations.AddConstraint(
            model_name='thumbnail',
            constraint=models.UniqueConstraint(fields=('video', 'position'), name='unique_thumbnail_position'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playlist', verbose_name='Playlist'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.video', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='historicalplaylistvideo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalplaylistvideo',
            name='playlist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.playlist', verbose_name='Playlist'),
        ),
        migrations.AddField(
            model_name='historicalplaylistvideo',
            name='video',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.video', verbose_name='Video'),
        ),
        migrations.AddConstraint(
            model_name='playlistvideo',
            constraint=models.UniqueConstraint(fields=('video', 'position'), name='unique_video_position'),
        ),
    ]
