# Generated by Django 3.1 on 2020-08-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200822_0641'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlistvideo',
            constraint=models.UniqueConstraint(fields=('playlist', 'video'), name='unique_playlist_video'),
        ),
    ]
