# Generated by Django 3.1 on 2020-08-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.ManyToManyField(to='core.Playlist', verbose_name='Playlist'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(to='core.Tag', verbose_name='Tag'),
        ),
    ]
