# Generated by Django 3.1 on 2020-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200824_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalplaylistvideo',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Playlist Video'},
        ),
        migrations.AlterModelOptions(
            name='playlistvideo',
            options={'ordering': ['playlist__name', 'position'], 'verbose_name': 'Playlist Video', 'verbose_name_plural': 'Playlist Video'},
        ),
        migrations.RemoveConstraint(
            model_name='playlistvideo',
            name='unique_video_position',
        ),
        migrations.AddConstraint(
            model_name='playlistvideo',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='unique_playlist_position'),
        ),
    ]
