# Generated by Django 3.1 on 2020-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200814_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvideo',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.ManyToManyField(blank=True, to='core.Playlist', verbose_name='Playlist'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(blank=True, to='core.Tag', verbose_name='Tag'),
        ),
    ]
