# Generated by Django 3.1 on 2020-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200814_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltag',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='historicalvideo',
            name='video',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Video'),
        ),
    ]
