# Generated by Django 3.1 on 2020-08-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200814_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.video', verbose_name='Video')),
            ],
        ),
        migrations.AddConstraint(
            model_name='thumbnail',
            constraint=models.UniqueConstraint(fields=('video', 'position'), name='unique_position'),
        ),
    ]
