# Generated by Django 3.1 on 2020-08-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200814_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvideo',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
    ]
