# Generated by Django 3.1 on 2020-08-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200815_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvideo',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PRO', 'Processing'), ('UPL', 'Uploading'), ('REA', 'Ready')], default='NEW', max_length=3),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PRO', 'Processing'), ('UPL', 'Uploading'), ('REA', 'Ready')], default='NEW', max_length=3),
        ),
    ]
